# Generated by Django 2.2 on 2019-05-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('cardID', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Card ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('cardSet', models.CharField(choices=[(0, 'Basic'), (1, 'Classic'), (2, 'Promo'), (3, 'Hall of Fame'), (4, 'Naxxramas'), (5, 'Goblins vs Gnomes'), (6, 'Blackrock Mountain'), (7, 'The Grand Tournament'), (8, 'The League of Explorers'), (9, 'Whispers of the Old Gods'), (10, 'One Night in Karazhan'), (11, 'Mean Streets of Gadgetzan'), (12, "Journey to Un'Goro"), (13, 'Knights of the Frozen Throne'), (14, 'Kobolds & Catacombs'), (15, 'The Witchwood'), (16, 'The Boomsday Project'), (17, "Rastakhan's Rumble"), (18, 'Rise of Shadows'), (19, 'Tavern Brawl'), (20, 'Taverns of Time'), (21, 'Hero Skins'), (22, 'Missions'), (23, 'Credits'), (24, 'System'), (25, 'Debug')], max_length=100, verbose_name='Card Set')),
                ('type', models.CharField(choices=[(0, 'Hero'), (1, 'Minion'), (2, 'Spell'), (3, 'Enchantment'), (4, 'Weapon'), (5, 'Hero Power')], max_length=30, verbose_name='Type')),
                ('rarity', models.CharField(choices=[(0, 'Free'), (1, 'Common'), (2, 'Rare'), (3, 'Epic'), (4, 'Legendary')], max_length=30, verbose_name='Rarity')),
                ('cost', models.IntegerField(verbose_name='Cost')),
                ('attack', models.IntegerField(null=True, verbose_name='Attack')),
                ('health', models.IntegerField(null=True, verbose_name='Health')),
                ('text', models.TextField(default='', verbose_name='Text')),
                ('race', models.CharField(choices=[(0, 'Demon'), (1, 'Dragon'), (2, 'Elemental'), (3, 'Mech'), (4, 'Murloc'), (5, 'Beast'), (6, 'Pirate'), (7, 'Totem')], max_length=30, verbose_name='Race')),
                ('playerClass', models.CharField(choices=[(0, 'Druid'), (1, 'Hunter'), (2, 'Mage'), (3, 'Paladin'), (4, 'Priest'), (5, 'Rogue'), (6, 'Shaman'), (7, 'Warlock'), (8, 'Warrior'), (9, 'Dream'), (10, 'Neutral'), (None, '')], max_length=30, verbose_name='Player Class')),
                ('img', models.URLField(verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=2000, verbose_name='Description')),
                ('playerClass', models.IntegerField(choices=[(0, 'Druid'), (1, 'Hunter'), (2, 'Mage'), (3, 'Paladin'), (4, 'Priest'), (5, 'Rogue'), (6, 'Shaman'), (7, 'Warlock'), (8, 'Warrior'), (9, 'Dream'), (10, 'Neutral'), (None, '')], verbose_name='Player Class')),
                ('deckString', models.CharField(max_length=500, verbose_name='Deck String')),
                ('image', models.CharField(default='', max_length=2000, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='CardsInDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOfCards', models.IntegerField(verbose_name='Number of Cards')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HSDT.Card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HSDT.Deck')),
            ],
        ),
    ]
