# Generated by Django 2.2 on 2019-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSDT', '0002_auto_20190509_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='playerClass',
            field=models.IntegerField(choices=[(0, 'Druid'), (1, 'Hunter'), (2, 'Mage'), (3, 'Paladin'), (4, 'Priest'), (5, 'Rogue'), (6, 'Shaman'), (7, 'Warlock'), (8, 'Warrior'), (9, 'Dream'), (10, 'Neutral'), (None, '')], max_length=30, verbose_name='Player Class'),
        ),
    ]
