# Generated by Django 2.2 on 2019-05-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HSDT', '0004_auto_20190509_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='DeckStringID',
        ),
        migrations.AlterField(
            model_name='cards',
            name='attack',
            field=models.IntegerField(null=True, verbose_name='Attack'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='health',
            field=models.IntegerField(null=True, verbose_name='Health'),
        ),
    ]
